blank_issues_enabled: false
contact_links:
  - name: Security vulnerability
    url: https://github.com/sauberdigital/dynamic-forms-bundle/security/policy
    about: Please do not open a public issue. See SECURITY policy.
